[tool.pyright]
reportMissingImports = "none"
reportMissingTypeStubs = false
reportOptionalCall = "none"
reportOptionalMemberAccess = "none"
reportOptionalOperand = "none"
reportCallIssue = "warning"
reportArgumentType = "warning"
reportAttributeAccessIssue = "warning"
reportOperatorIssue = "warning"
pythonVersion = "3.11"
typeCheckingMode = "basic"

[tool.basedpyright]
reportMissingImports = "none"
reportMissingTypeStubs = false
reportOptionalCall = "none"
reportOptionalMemberAccess = "none"
reportOptionalOperand = "none"
reportCallIssue = "warning"
reportArgumentType = "warning"
reportAttributeAccessIssue = "warning"
reportOperatorIssue = "warning"
pythonVersion = "3.11"
typeCheckingMode = "basic"

